services:
  app:
    image: dunglas/frankenphp
    networks:
      - app
    ports:
      - "80:80"
      - "443:443" 
      - "443:443/udp"
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    # comment the following line in production, it allows to have nice human-readable logs in dev
    # tty: true
    depends_on:
      - composer

  composer:
    image: composer:2.2
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: ["composer", "--ignore-platform-reqs", "--no-progress", "--no-ansi"]
    command: ["install"]

networks:
  app:
    driver: bridge

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
  mysql:
    driver: local
