services:
  app:
    image: dunglas/frankenphp
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app
    ports:
      - "80:80"
      - "443:443" 
      - "443:443/udp"
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    # comment the following line in production, it allows to have nice human-readable logs in dev
    # tty: true
    depends_on:
      - composer
      - mysql

  composer:
    image: composer:2.2
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: ["composer", "--ignore-platform-reqs", "--no-progress", "--no-ansi"]
    command: ["install"]

  mysql:
    image: mysql:8.3
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      interval: 10s 
      retries: 3
      timeout: 5s

networks:
  app:
    driver: bridge

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
  mysql:
    driver: local
